@BuberBreakfast_HostAddress = http://localhost:5049

POST {{BuberBreakfast_HostAddress}}/breakfasts/
Content-Type: application/json

{
    "name": "Vegan Sunshine - Deluxe",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad",
        "Celery"
    ],
    "Sweet": [
        "Cookie",
        "Dates"
    ]
}

###

GET {{BuberBreakfast_HostAddress}}/Breakfasts/c2cb1f2d-7f8b-49a3-8c49-05f2c4102171